"use client";
import {useEffect,useState,useCallback} from "react";
import {CarFront,Truck,Plus,Search,Users,Wrench,FileText,ArrowUpRight,ShieldCheck,Download,Printer,Pencil,Trash2,History as HistoryIcon,UserRound,Check,RefreshCw,Info,ArrowRight,X} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from "@/components/ui/alert-dialog";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from "@/components/ui/empty";
import {Skeleton} from "@/components/ui/skeleton";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {statuses,clean,day,dateLabel,shortDate,inPeriod,csvCell,type Vehicle,type Fleet,type Status} from "@/lib/fleet";
const newVehicle={model:"",plate:"",person:"",maintenance:"unknown" as Status,due_date:"",maintenance_notes:"",notes:""};
type Form=typeof newVehicle&{id?:string;revision?:number};
function Pick({value,onChange,options,label,className=""}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string;className?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className={`filter-select ${className}`}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Badge({status}:{status:Status}){return <span className={`pill ${status}`}>{status==="ok"?<Check/>:status==="pending"||status==="in_progress"?<Wrench/>:null}{statuses[status]}</span>}
function NoResults({title="Nenhum veículo encontrado",description="Tente outra busca ou ajuste os filtros."}:{title?:string;description?:string}){return <Empty className="empty"><EmptyHeader><EmptyMedia variant="icon"><CarFront/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>}
export default function Home({embedded=false,csrfToken="",onUnauthorized,onFleetChange}:{embedded?:boolean;csrfToken?:string;onUnauthorized?:()=>void;onFleetChange?:(fleet:Fleet)=>void}={}){
 const [data,setData]=useState<Fleet>({vehicles:[],history:[]}),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 const [tab,setTab]=useState("fleet"),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[assignment,setAssignment]=useState("all"),[page,setPage]=useState(1);
 const [form,setForm]=useState<Form|null>(null),[formError,setFormError]=useState(""),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState<Vehicle|null>(null),[detail,setDetail]=useState<Vehicle|null>(null);
 const [from,setFrom]=useState(""),[to,setTo]=useState(""),[reportPerson,setReportPerson]=useState(""),[reportVehicle,setReportVehicle]=useState("all"),[reportStatus,setReportStatus]=useState("all"),[reportPage,setReportPage]=useState(1);
 const [today,setToday]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setLoadError("");try{const r=await fetch("/api/fleet",{cache:"no-store"});const d=await r.json() as Fleet & {error?:string};if(!r.ok){if(r.status===401||r.status===428)onUnauthorized?.();throw new Error(d.error);}setData(d);onFleetChange?.(d);}catch(e){setLoadError(e instanceof Error?e.message:"Não foi possível carregar a frota.");}finally{setLoading(false)}},[onUnauthorized,onFleetChange]);
 useEffect(()=>{refresh();setToday(day(new Date().toISOString()))},[refresh]);
 useEffect(()=>{setPage(1)},[search,status,assignment]);
 useEffect(()=>{setReportPage(1)},[from,to,reportPerson,reportVehicle,reportStatus]);
 const active=data.vehicles.filter(v=>!v.deleted_at),assigned=active.filter(v=>v.person),maintenance=active.filter(v=>["pending","in_progress"].includes(v.maintenance)),unknown=active.filter(v=>v.maintenance==="unknown");
 const filtered=active.filter(v=>clean(`${v.model} ${v.plate} ${v.person} ${v.notes}`).includes(clean(search))&&(status==="all"||v.maintenance===status)&&(assignment==="all"||(assignment==="assigned"?!!v.person:!v.person)));
 const pages=Math.max(1,Math.ceil(filtered.length/20)),currentPage=Math.min(page,pages),displayed=filtered.slice((currentPage-1)*20,currentPage*20);
 const dateError=from&&to&&from>to?"A data inicial deve ser anterior ou igual à data final.":"";
 const reportRows=dateError?[]:data.history.filter(h=>inPeriod(h,from,to)&&clean(h.person).includes(clean(reportPerson))&&(reportVehicle==="all"||h.vehicle_id===reportVehicle)&&(reportStatus==="all"||h.maintenance===reportStatus));
 const reportPages=Math.max(1,Math.ceil(reportRows.length/30)),rp=Math.min(reportPage,reportPages);
 const reportSummary=`Período: ${from?shortDate(from):"todo o histórico"}${to?" até "+shortDate(to):""} · Pessoa: ${reportPerson||"todas"} · Veículo: ${reportVehicle==="all"?"todos":data.vehicles.find(v=>v.id===reportVehicle)?.plate} · Manutenção: ${reportStatus==="all"?"todas":statuses[reportStatus as Status]}`;
 function edit(v?:Vehicle){setFormError("");setForm(v?{...v}:{...newVehicle})}
 async function mutate(body:unknown){const r=await fetch("/api/fleet",{method:"POST",headers:{"Content-Type":"application/json",...(csrfToken?{"X-CSRF-Token":csrfToken}:{})},body:JSON.stringify(body)});let d:{error?:string};try{d=await r.json() as {error?:string}}catch{throw new Error("A conexão foi interrompida. Atualize a frota para conferir se a operação foi salva.")}if(r.status===401||r.status===428)onUnauthorized?.();if(!r.ok)throw new Error(d.error||"Não foi possível salvar. Tente novamente.");return d;}
 async function save(e:React.FormEvent){e.preventDefault();if(!form||busy)return;setBusy(true);setFormError("");try{await mutate({...form,action:form.id?"update":"create"});setForm(null);toast.success(form.id?"Veículo atualizado. Histórico preservado.":"Veículo cadastrado.");await refresh()}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function remove(){if(!deleting||busy)return;setBusy(true);setFormError("");try{await mutate({action:"delete",id:deleting.id,revision:deleting.revision});setDeleting(null);toast.success("Veículo excluído da frota. Histórico preservado.");await refresh()}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 function exportCSV(){const rows=[["Modelo","Placa","Responsável","Situação de manutenção","Previsão de manutenção","Início (Brasília)","Fim (Brasília)","Registro","Serviço / manutenção","Observações","Veículo excluído"],...reportRows.map(h=>[h.model,h.plate,h.person||"Sem responsável",statuses[h.maintenance],shortDate(h.due_date),dateLabel(h.started_at),dateLabel(h.ended_at||""),h.event,h.maintenance_notes,h.notes,data.vehicles.find(v=>v.id===h.vehicle_id)?.deleted_at?"Sim":"Não"])];const blob=new Blob(["\uFEFF"+rows.map(row=>row.map(csvCell).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`VOLTS-relatorio-frota-${today||"exportacao"}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success(`${reportRows.length} ${reportRows.length===1?"registro exportado":"registros exportados"}.`)}
 function printReport(){document.body.classList.add("printing");window.print();document.body.classList.remove("printing")}
 return <div className={`app ${embedded?"embedded-fleet":""}`}>{!embedded&&<Toaster theme="dark" position="bottom-right"/>}<header className="topbar"><div className="brand"><div><div className="wordmark">VOLTS</div><div className="brand-sub">AUTOMAÇÃO E MANUTENÇÃO ELÉTRICA</div></div><div className="brand-rule"/><div className="brand-cog"><strong>COG</strong>GESTÃO DE FROTA</div></div><div className="workspace-label"><ShieldCheck/> CONTROLE OPERACIONAL</div></header>
 <main className="main"><div className="page-heading"><div><p className="eyebrow">OPERAÇÃO EM MOVIMENTO</p><h1>Gestão de frota<span style={{color:"#fff500"}}>.</span></h1><p className="subtitle">Acompanhe veículos, responsáveis e manutenções.</p></div><div className="heading-actions"><button className="btn" onClick={()=>setTab("reports")}><FileText/>Relatórios<ArrowUpRight size={15}/></button><button className="btn btn-primary" disabled={loading||!!loadError} onClick={()=>edit()}><Plus/>Novo veículo</button></div></div>
 <section className="metrics" aria-label="Resumo da frota">{[{label:"Total de veículos",value:active.length,caption:"Veículos cadastrados na frota",Icon:CarFront},{label:"Com responsável",value:assigned.length,caption:`${active.length-assigned.length} sem responsável definido`,Icon:Users},{label:"Precisam de manutenção",value:maintenance.length,caption:`${maintenance.filter(v=>v.maintenance==="in_progress").length} em manutenção neste momento`,Icon:Wrench},{label:"Manutenção em dia",value:active.filter(v=>v.maintenance==="ok").length,caption:`${unknown.length} com situação não informada`,Icon:ShieldCheck}].map(m=><article className="metric" key={m.label}><div className="metric-label">{m.label}<m.Icon/></div><div className="metric-value">{loading?<Skeleton className="h-10 w-12"/>:loadError?"—":String(m.value).padStart(2,"0")}</div><div className="metric-caption">{loading?"Carregando…":loadError?"Dados indisponíveis":m.caption}</div></article>)}</section>
 {loadError?<div className="error-box" role="alert">{loadError}<button className="btn btn-ghost" onClick={refresh}><RefreshCw/>Tentar novamente</button></div>:null}
 <Tabs className="section-tabs" value={tab} onValueChange={setTab}><TabsList aria-label="Seções da gestão de frota"><TabsTrigger value="fleet"><CarFront/>Frota <span className="tab-count">{loading?"—":active.length}</span></TabsTrigger><TabsTrigger value="maintenance"><Wrench/>Manutenções{maintenance.length>0&&<span className="tab-count">{maintenance.length}</span>}</TabsTrigger><TabsTrigger value="reports"><FileText/>Relatórios</TabsTrigger></TabsList>
 <TabsContent value="fleet"><section className="panel"><div className="panel-heading"><h2>Veículos da frota</h2><button className="btn btn-ghost small muted" onClick={refresh} disabled={loading}><RefreshCw size={15}/>Atualizar</button></div><div className="toolbar"><div className="searchbox"><Search/><input className="field-input" aria-label="Buscar veículo, placa ou responsável" placeholder="Buscar veículo, placa ou responsável…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Pick label="Filtrar manutenção" value={status} onChange={setStatus} options={[["all","Todas as manutenções"],...Object.entries(statuses)]}/><Pick label="Filtrar responsável" value={assignment} onChange={setAssignment} options={[["all","Todos os responsáveis"],["assigned","Com responsável"],["unassigned","Sem responsável"]]}/></div>
 {loading?<div className="p-6 space-y-4" aria-label="Carregando veículos">{[1,2,3,4].map(n=><Skeleton key={n} className="h-12 w-full"/>)}</div>:filtered.length===0?<NoResults description={active.length?"Tente outra busca ou ajuste os filtros.":"Cadastre um veículo para começar."}/>:<Table className="fleet-table"><TableHeader><TableRow><TableHead>Veículo</TableHead><TableHead>Placa</TableHead><TableHead>Responsável</TableHead><TableHead>Manutenção</TableHead><TableHead>Observações</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{displayed.map(v=><TableRow key={v.id}><TableCell><div className="vehicle-name"><span className="vehicle-icon">{/VM|Agrale/i.test(v.model)?<Truck/>:<CarFront/>}</span><div><strong>{v.model}</strong><small>{/VM|Agrale/i.test(v.model)?"Veículo de apoio":"Veículo operacional"}</small></div></div></TableCell><TableCell><span className="plate">{v.plate}</span></TableCell><TableCell><div className={`person ${!v.person?"muted":""}`}><UserRound/>{v.person||"Sem responsável"}</div></TableCell><TableCell><Badge status={v.maintenance}/>{v.due_date&&["pending","in_progress"].includes(v.maintenance)&&<div className="small muted mt-1">{shortDate(v.due_date)}{v.due_date<today?" · Atrasada":""}</div>}</TableCell><TableCell><div className="note-preview" title={v.notes||"Nenhuma observação"}>{v.notes||"—"}</div></TableCell><TableCell><div className="row-actions"><button className="btn btn-ghost" title="Ver histórico" aria-label={`Histórico de ${v.plate}`} onClick={()=>setDetail(v)}><HistoryIcon/></button><button className="btn btn-ghost" title="Editar veículo" aria-label={`Editar ${v.plate}`} onClick={()=>edit(v)}><Pencil/></button><button className="btn btn-ghost muted" title="Excluir veículo" aria-label={`Excluir ${v.plate}`} onClick={()=>{setDeleting(v);setFormError("")}}><Trash2/></button></div></TableCell></TableRow>)}</TableBody></Table>}
 <div className="table-footer"><span>{loading?"Carregando…":`${filtered.length} ${filtered.length===1?"veículo encontrado":"veículos encontrados"}`}</span>{pages>1?<div><button className="btn btn-ghost" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Anterior</button>{currentPage} / {pages}<button className="btn btn-ghost" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Próxima</button></div>:<span>VOLTS · Controle de frota do COG</span>}</div></section></TabsContent>
 <TabsContent value="maintenance">{unknown.length>0&&<div className="notice"><Info/><span>{unknown.length} {unknown.length===1?"veículo ainda precisa":"veículos ainda precisam"} de avaliação. Atualize a situação no cadastro de cada veículo.</span></div>}<div className="panel-heading" style={{padding:"0 0 20px"}}><h2>Manutenções em aberto</h2><span className="small muted">{maintenance.length} {maintenance.length===1?"veículo":"veículos"}</span></div>{loading?<Skeleton className="h-40 w-full"/>:maintenance.length===0?<div className="panel"><NoResults title="Nenhuma manutenção em aberto" description="As manutenções pendentes ou em andamento aparecerão aqui."/></div>:<div className="maintenance-grid">{[...maintenance].sort((a,b)=>(a.due_date||"9999").localeCompare(b.due_date||"9999")).map(v=><article key={v.id} className="maintenance-card"><header><div className="vehicle-name"><span className="vehicle-icon"><Wrench/></span><div><strong>{v.model}</strong><small>{v.plate}</small></div></div><Badge status={v.maintenance}/></header><p>{v.maintenance_notes||"Serviço não descrito."}</p><div className="person small"><UserRound/>{v.person||"Sem responsável"}</div><footer><span className="small" style={{color:v.due_date&&v.due_date<today?"#ffd07b":"#aab7a5"}}>{v.due_date&&v.due_date<today?"Atrasada · ":"Previsão · "}{shortDate(v.due_date)}</span><button className="btn" onClick={()=>edit(v)}>Atualizar<ArrowRight/></button></footer></article>)}</div>}</TabsContent>
 <TabsContent value="reports"><section className="panel"><div className="print-heading"><strong>VOLTS · COG</strong><p>Relatório de histórico da frota • Emitido em {dateLabel(new Date().toISOString())}</p><p>{reportSummary}</p></div><div className="panel-heading"><h2>Histórico por período</h2><div className="heading-actions"><button className="btn" onClick={printReport} disabled={!reportRows.length||!!dateError||loading}><Printer/>Imprimir / PDF</button><button className="btn btn-primary" onClick={exportCSV} disabled={!reportRows.length||!!dateError||loading}><Download/>Exportar CSV</button></div></div><div className="report-filters"><label className="form-field">Responsável<input className="field-input" placeholder="Nome da pessoa" value={reportPerson} onChange={e=>setReportPerson(e.target.value)}/></label><label className="form-field">Data inicial<input className="field-input" type="date" value={from} onChange={e=>setFrom(e.target.value)} onInput={e=>setFrom(e.currentTarget.value)}/></label><label className="form-field">Data final<input className="field-input" type="date" value={to} onChange={e=>setTo(e.target.value)} onInput={e=>setTo(e.currentTarget.value)}/></label><div className="form-field"><span>Veículo</span><Pick label="Veículo no relatório" value={reportVehicle} onChange={setReportVehicle} options={[["all","Todos os veículos"],...data.vehicles.map(v=>[v.id,`${v.plate} · ${v.model}${v.deleted_at?" (excluído)":""}`] as [string,string])]}/></div><div className="form-field"><span>Manutenção</span><Pick label="Manutenção no relatório" value={reportStatus} onChange={setReportStatus} options={[["all","Todas as situações"],...Object.entries(statuses)]}/></div></div><p className="report-intro">Cada linha mostra a situação do veículo durante um intervalo. O filtro inclui os intervalos que passam pelo período selecionado, inclusive os de veículos excluídos. Datas e horários de Brasília.<br/><strong>{reportRows.length} {reportRows.length===1?"registro":"registros"} · {new Set(reportRows.map(h=>h.vehicle_id)).size} {new Set(reportRows.map(h=>h.vehicle_id)).size===1?"veículo":"veículos"}</strong>{(from||to||reportPerson||reportVehicle!=="all"||reportStatus!=="all")&&<button className="btn btn-ghost no-print" onClick={()=>{setFrom("");setTo("");setReportPerson("");setReportVehicle("all");setReportStatus("all")}}>Limpar filtros<X size={14}/></button>}</p>{dateError&&<div className="error-box mx-6" role="alert">{dateError}</div>}
 {loading?<Skeleton className="h-40 mx-6"/>:reportRows.length===0?<NoResults title="Nenhum registro neste filtro" description="Altere o período, o responsável ou a situação para consultar outros registros."/>:<><Table className="fleet-table report-table"><TableHeader><TableRow><TableHead>Veículo / placa</TableHead><TableHead>Responsável</TableHead><TableHead>Intervalo</TableHead><TableHead>Manutenção</TableHead><TableHead>Previsão</TableHead><TableHead>Serviço e observações</TableHead></TableRow></TableHeader><TableBody>{reportRows.map((h,i)=><TableRow key={h.id} className={i<(rp-1)*30||i>=rp*30?"print-only-row":""}><TableCell><strong>{h.model}</strong><div className="mt-2"><span className="plate">{h.plate}</span></div>{data.vehicles.find(v=>v.id===h.vehicle_id)?.deleted_at&&<div className="small muted mt-1">Excluído da frota</div>}</TableCell><TableCell>{h.person||"Sem responsável"}</TableCell><TableCell><div className="report-date">{dateLabel(h.started_at)}<br/>até {dateLabel(h.ended_at||"")}</div><div className="small muted mt-1">{h.event}</div></TableCell><TableCell><Badge status={h.maintenance}/></TableCell><TableCell>{shortDate(h.due_date)}</TableCell><TableCell><div className="report-notes">{h.maintenance_notes&&<div><strong>Serviço: </strong>{h.maintenance_notes}</div>}{h.notes&&<div><strong>Obs.: </strong>{h.notes}</div>}{!h.maintenance_notes&&!h.notes?"—":null}</div></TableCell></TableRow>)}</TableBody></Table><div className="table-footer"><span>{reportRows.length} registros no relatório · Exportação inclui todos os resultados</span>{reportPages>1&&<div><button className="btn btn-ghost" disabled={rp===1} onClick={()=>setReportPage(rp-1)}>Anterior</button>{rp} / {reportPages}<button className="btn btn-ghost" disabled={rp===reportPages} onClick={()=>setReportPage(rp+1)}>Próxima</button></div>}</div></>}</section></TabsContent></Tabs>
 <footer className="app-footer"><span>VOLTS / COG</span><span>Automação e manutenção elétrica</span></footer></main>
 <Dialog open={!!form} onOpenChange={open=>{if(!open&&!busy)setForm(null)}}><DialogContent className="dialog-body" showCloseButton={false}><DialogHeader><DialogTitle>{form?.id?"Editar veículo":"Novo veículo"}</DialogTitle><DialogDescription>Cadastre o veículo e mantenha os dados da operação atualizados.</DialogDescription></DialogHeader>{form&&<form onSubmit={save}><div className="form-grid"><label className="form-field">Modelo / identificação *<input autoFocus required maxLength={80} className="field-input" placeholder="Ex.: Oroch" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label className="form-field">Placa *<input required maxLength={9} pattern="[A-Za-z]{3}[- ]?[0-9][A-Za-z0-9][0-9]{2}" className="field-input uppercase" placeholder="Ex.: ABC1D23" value={form.plate} onChange={e=>setForm({...form,plate:e.target.value.toUpperCase()})}/></label><label className="form-field full">Responsável atual<input maxLength={100} className="field-input" placeholder="Nome da pessoa que está com o veículo" value={form.person} onChange={e=>setForm({...form,person:e.target.value})}/><span className="muted small">Deixe em branco quando o veículo estiver sem responsável. As trocas ficam no histórico.</span></label><div className="form-divider">Manutenção</div><div className="form-field"><span>Situação *</span><Pick label="Situação de manutenção" value={form.maintenance} onChange={v=>setForm({...form,maintenance:v as Status})} options={Object.entries(statuses)}/></div><label className="form-field">Previsão de manutenção<input className="field-input" type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} onInput={e=>setForm({...form,due_date:e.currentTarget.value})}/></label><label className="form-field full">Serviço / detalhes da manutenção{["pending","in_progress"].includes(form.maintenance)?" *":""}<textarea required={["pending","in_progress"].includes(form.maintenance)} maxLength={4000} className="field-input" placeholder="Descreva o que precisa ser feito ou o serviço realizado." value={form.maintenance_notes} onChange={e=>setForm({...form,maintenance_notes:e.target.value})}/></label><div className="form-divider">Observações</div><label className="form-field full"><span>Observações da operação</span><textarea maxLength={4000} className="field-input" placeholder="Condição do veículo, pendências ou informações importantes…" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{formError&&<p className="error-box" role="alert">{formError}</p>}<div className="dialog-buttons"><button type="button" className="btn" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button type="submit" className="btn btn-primary" disabled={busy}>{busy?"Salvando…":form.id?"Salvar alterações":"Cadastrar veículo"}</button></div></form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>{if(!open&&!busy)setDeleting(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir {deleting?.model} · {deleting?.plate}?</AlertDialogTitle><AlertDialogDescription>O veículo será removido da frota ativa. O histórico de responsáveis, manutenções e observações continuará disponível nos relatórios.</AlertDialogDescription></AlertDialogHeader>{formError&&<p className="error-box" role="alert">{formError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><button className="btn btn-danger" onClick={remove} disabled={busy}>{busy?"Excluindo…":"Excluir veículo"}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="dialog-body" showCloseButton={false}><DialogHeader><DialogTitle>Histórico do veículo</DialogTitle><DialogDescription>{detail?.model} · {detail?.plate} — alterações e períodos de uso.</DialogDescription></DialogHeader><div className="history-list">{data.history.filter(h=>h.vehicle_id===detail?.id).map(h=><article className="history-item" key={h.id}><time>{dateLabel(h.started_at)} até {dateLabel(h.ended_at||"")}</time><h3>{h.event}</h3><Badge status={h.maintenance}/><p><strong>Responsável: </strong>{h.person||"Sem responsável"}</p>{h.due_date&&<p><strong>Previsão: </strong>{shortDate(h.due_date)}</p>}{h.maintenance_notes&&<p><strong>Manutenção: </strong>{h.maintenance_notes}</p>}{h.notes&&<p><strong>Observações: </strong>{h.notes}</p>}</article>)}</div><div className="dialog-buttons"><button className="btn" onClick={()=>setDetail(null)}>Fechar</button></div></DialogContent></Dialog>
 </div>;
}



