import {useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {Archive,ArchiveRestore,ArrowDownLeft,ArrowUpRight,Check,Clock,Download,FileText,History,KeyRound,MapPin,Pencil,Plus,Printer,RefreshCw,Search} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
import {day,dateLabel} from '@/lib/fleet';
import {containsText,dateOnlyLabel,filterKeyLoans,keyCategories,keysCSV,loanStatus,loanStatuses,localKeyTime,type KeyLoan,type KeyRecord} from './keys-utils';
import './keys.css';

type KeyData={keys:KeyRecord[];loans:KeyLoan[]};
type KeyForm={mode:'create'|'edit'|'checkout'|'return';key?:KeyRecord;loan?:KeyLoan;name:string;code:string;location:string;category:string;notes:string;withCheckout:boolean;holder:string;checked_out_at:string;expected_return:string;checkout_notes:string;returned_at:string;return_notes:string};
function Field({label,children,full=false}:{label:string;children:ReactNode;full?:boolean}){return <label className={`form-field ${full?'full':''}`}><span>{label}</span>{children}</label>}
function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="field-input cog-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select>}
function Badge({status}:{status:string}){return <span className={`key-status ${status}`}>{({available:'Disponível',archived:'Arquivada',...loanStatuses})[status]}</span>}
function Empty({children}:{children:ReactNode}){return <div className="cog-empty"><KeyRound/><p>{children}</p></div>}

export default function Keys({isAdmin,csrfToken,onUnauthorized}:{isAdmin:boolean;csrfToken:string;onUnauthorized:()=>void}){
 const [data,setData]=useState<KeyData>({keys:[],loans:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('inventory');
 const [form,setForm]=useState<KeyForm|null>(null),[formError,setFormError]=useState(''),[historyId,setHistoryId]=useState(''),[archive,setArchive]=useState<KeyRecord|null>(null);
 const [search,setSearch]=useState(''),[location,setLocation]=useState(''),[category,setCategory]=useState('all'),[holder,setHolder]=useState(''),[status,setStatus]=useState('active');
 const today=day(new Date().toISOString());
 const [report,setReport]=useState({from:today.slice(0,7)+'-01',to:today,person:'',location:'',keyId:'all',status:'all'});
 const [page,setPage]=useState(1),[reportPage,setReportPage]=useState(1);
 const mutationInFlight=useRef(false),mounted=useRef(true),loadSequence=useRef(0);
 async function request(body?:unknown){
  const response=await fetch('/api/keys',{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify(body)}:{})});
  const result=await response.json() as KeyData & {error?:string};
  if(!response.ok){if(response.status===401||response.status===428)onUnauthorized();throw Object.assign(Error(result.error||'Não foi possível concluir a operação.'),{status:response.status});}
  return result;
 }
 async function reload(){const sequence=++loadSequence.current;setLoading(true);setError('');try{const result=await request();if(mounted.current&&sequence===loadSequence.current)setData(result);}catch(e){if(mounted.current&&sequence===loadSequence.current)setError((e as Error).message);}finally{if(mounted.current&&sequence===loadSequence.current)setLoading(false);}}
 useEffect(()=>{mounted.current=true;reload();return()=>{mounted.current=false;loadSequence.current++;};},[]);
 useEffect(()=>{setPage(1);},[search,location,category,holder,status]);
 useEffect(()=>{setReportPage(1);},[report]);
 const openLoans=new Map(data.loans.filter(loan=>!loan.returned_at).map(loan=>[loan.key_id,loan]));
 const activeKeys=data.keys.filter(key=>!key.archived_at);
 const overdue=data.loans.filter(loan=>loanStatus(loan,today)==='overdue').length;
 const inventory=data.keys.filter(key=>{
  const loan=openLoans.get(key.id),current=key.archived_at?'archived':loan?loanStatus(loan,today):'available';
  return (status==='all'||status==='active'&&!key.archived_at||status==='out'&&!!loan&&!key.archived_at||status===current)&&containsText(`${key.name} ${key.code} ${key.notes}`,search)&&containsText(key.location,location)&&(category==='all'||key.category===category)&&containsText(loan?.holder||'',holder);
 });
 const selectedKey=data.keys.find(key=>key.id===historyId),history=data.loans.filter(loan=>loan.key_id===historyId);
 const reportError=report.from&&report.to&&report.from>report.to?'A data inicial deve ser anterior ou igual à data final.':report.from>today||report.to>today?'Consulte datas até hoje. O relatório mostra movimentações já registradas.':'';
 const reportLoans=reportError?[]:filterKeyLoans(data.loans,report,today);
 const currentPage=Math.min(page,Math.max(1,Math.ceil(inventory.length/20))),currentReportPage=Math.min(reportPage,Math.max(1,Math.ceil(reportLoans.length/30)));
 function openForm(mode:KeyForm['mode'],key?:KeyRecord){setFormError('');setForm({mode,key,loan:key?openLoans.get(key.id):undefined,name:key?.name||'',code:key?.code||'',location:key?.location||'',category:key?.category||'work',notes:key?.notes||'',withCheckout:true,holder:'',checked_out_at:localKeyTime(),expected_return:'',checkout_notes:'',returned_at:localKeyTime(),return_notes:''});}
 function edit(field:keyof KeyForm,value:string|boolean){setForm(current=>current?{...current,[field]:value}:null);}
 async function save(event:FormEvent){
  event.preventDefault();if(!form||mutationInFlight.current)return;mutationInFlight.current=true;setBusy(true);setFormError('');
  try{
   let body:Record<string,unknown>={action:`key.${form.mode==='edit'?'update':form.mode}`,id:form.key?.id,revision:form.key?.revision};
   if(form.mode==='create'||form.mode==='edit')body={...body,name:form.name,code:form.code,location:form.location,category:form.category,notes:form.notes};
   const checkout={holder:form.holder,checked_out_at:form.checked_out_at,expected_return:form.expected_return,notes:form.checkout_notes};
   if(form.mode==='create'&&form.withCheckout)body.checkout=checkout;
   if(form.mode==='checkout')body={...body,...checkout};
   if(form.mode==='return')body={...body,loan_id:form.loan?.id,returned_at:form.returned_at,notes:form.return_notes};
   await request(body);if(!mounted.current)return;setForm(null);toast.success(form.mode==='return'?'Devolução registrada.':form.mode==='checkout'||form.mode==='create'&&form.withCheckout?'Chave e retirada registradas.':'Chave salva.');await reload();
  }catch(e){if(mounted.current){setFormError((e as Error).message+((e as Error & {status?:number}).status===409?' Feche esta janela e reabra a operação na lista atualizada.':''));await reload();}}finally{mutationInFlight.current=false;if(mounted.current)setBusy(false);}
 }
 async function archiveKey(){if(!archive||mutationInFlight.current)return;mutationInFlight.current=true;setBusy(true);try{await request({action:archive.archived_at?'key.restore':'key.archive',id:archive.id,revision:archive.revision});setArchive(null);toast.success(archive.archived_at?'Chave restaurada.':'Chave arquivada. O histórico foi mantido.');await reload();}catch(e){toast.error((e as Error).message);await reload();}finally{mutationInFlight.current=false;if(mounted.current)setBusy(false);}}
 function exportCSV(){const rows=[['Chave','Código','Local na retirada','Categoria na retirada','Pessoa que retirou','Saída (Brasília)','Previsão de devolução','Devolução (Brasília)','Situação atual da retirada','Observações da saída','Registrado por','Observações da devolução','Devolução registrada por'],...reportLoans.map(loan=>[loan.key_name,loan.key_code,loan.key_location,keyCategories[loan.key_category],loan.holder,dateLabel(loan.checked_out_at),loan.expected_return?dateOnlyLabel(loan.expected_return):'',loan.returned_at?dateLabel(loan.returned_at):'',loanStatuses[loanStatus(loan,today)],loan.checkout_notes,loan.checkout_author_name,loan.return_notes,loan.return_author_name])];const url=URL.createObjectURL(new Blob([keysCSV(rows)],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`VOLTS-chaves-${report.from||'inicio'}-${report.to||'hoje'}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function paginate(current:number,count:number,size:number,set:(page:number)=>void){return <div className="keys-pagination no-print"><span>{count} {count===1?'registro':'registros'} · Página {current} de {Math.max(1,Math.ceil(count/size))}</span><div><button className="btn btn-ghost" disabled={current<=1} onClick={()=>set(current-1)}>Anterior</button><button className="btn btn-ghost" disabled={current>=Math.ceil(count/size)} onClick={()=>set(current+1)}>Próxima</button></div></div>}
 const checkoutFields=<><Field label="Quem está retirando *" full><input className="field-input" required maxLength={120} autoComplete="off" value={form?.holder||''} onChange={e=>edit('holder',e.target.value)} placeholder="Nome da pessoa responsável pela chave"/></Field><Field label="Data e hora da saída *"><input className="field-input" type="datetime-local" required max={localKeyTime()} value={form?.checked_out_at||''} onChange={e=>edit('checked_out_at',e.target.value)}/></Field><Field label="Previsão de devolução"><input className="field-input" type="date" min={form?.checked_out_at.slice(0,10)} value={form?.expected_return||''} onChange={e=>edit('expected_return',e.target.value)}/></Field><Field label="Observações da saída" full><textarea className="field-input" maxLength={4000} value={form?.checkout_notes||''} onChange={e=>edit('checkout_notes',e.target.value)} placeholder="Destino, finalidade ou orientação para a devolução"/></Field></>;
 return <div className="keys-module">
  <div className="page-heading"><div><p className="eyebrow">CONTROLE DE RETIRADAS E DEVOLUÇÕES</p><h1>Registro de chaves.</h1><p className="subtitle">Saiba com quem estão as chaves das obras, usinas e alojamentos.</p></div><div className="heading-actions"><button className="btn" disabled={loading||busy} onClick={reload}><RefreshCw className={loading?'keys-spinning':''}/>Atualizar</button><button className="btn btn-primary" disabled={busy} onClick={()=>openForm('create')}><Plus/>Cadastrar chave</button></div></div>
  {error&&<p className="error-box" role="alert">{error}</p>}
  <div className="metrics keys-metrics"><article className="metric"><div className="metric-label"><KeyRound/>Chaves ativas</div><strong className="metric-value">{activeKeys.length}</strong><p className="metric-caption">Cadastros em uso</p></article><article className="metric"><div className="metric-label"><Check/>Disponíveis</div><strong className="metric-value">{activeKeys.filter(key=>!openLoans.has(key.id)).length}</strong><p className="metric-caption">Aguardando retirada</p></article><article className="metric"><div className="metric-label"><ArrowUpRight/>Retiradas</div><strong className="metric-value">{openLoans.size}</strong><p className="metric-caption">Em posse de uma pessoa</p></article><article className="metric"><div className="metric-label"><Clock/>Em atraso</div><strong className="metric-value">{overdue}</strong><p className="metric-caption">Previsão de devolução vencida</p></article></div>
  <Tabs className="section-tabs keys-tabs" value={tab} onValueChange={setTab}><TabsList aria-label="Consultas de chaves"><TabsTrigger value="inventory"><KeyRound/>Chaves cadastradas</TabsTrigger><TabsTrigger value="reports"><FileText/>Relatórios</TabsTrigger></TabsList>
   <TabsContent value="inventory"><section className="panel"><div className="keys-filters no-print"><Field label="Buscar chave"><div className="keys-search"><Search/><input className="field-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, código ou observação"/></div></Field><Field label="Local"><input className="field-input" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Obra, usina ou endereço"/></Field><div className="form-field"><span>Categoria</span><Pick label="Categoria das chaves" value={category} onChange={setCategory} options={[["all","Todas as categorias"],...Object.entries(keyCategories)]}/></div><Field label="Com quem está"><input className="field-input" value={holder} onChange={e=>setHolder(e.target.value)} placeholder="Nome da pessoa"/></Field><div className="form-field"><span>Situação</span><Pick label="Situação das chaves" value={status} onChange={setStatus} options={[["active","Todas as ativas"],["available","Disponíveis"],["out","Retiradas (inclui atrasadas)"],["overdue","Em atraso"],["archived","Arquivadas"],["all","Ativas e arquivadas"]]}/></div></div>
    {loading&&!data.keys.length?<Empty>Carregando as chaves…</Empty>:!data.keys.length?<Empty>Nenhuma chave cadastrada. Use <strong>Cadastrar chave</strong> quando registrar a primeira saída.</Empty>:!inventory.length?<Empty>Nenhuma chave corresponde aos filtros.</Empty>:<Table className="fleet-table keys-inventory"><TableHeader><TableRow>{['Chave / local','Categoria','Situação','Com quem está','Saída / previsão','Ações'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{inventory.slice((currentPage-1)*20,currentPage*20).map(key=>{const loan=openLoans.get(key.id);return <TableRow key={key.id}><TableCell><strong>{key.name}</strong>{key.code&&<span className="key-code">{key.code}</span>}<div className="keys-location"><MapPin/>{key.location||'Local não informado'}</div></TableCell><TableCell>{keyCategories[key.category]}</TableCell><TableCell><Badge status={key.archived_at?'archived':loan?loanStatus(loan,today):'available'}/></TableCell><TableCell>{loan?.holder||'—'}</TableCell><TableCell>{loan?<><span>{dateLabel(loan.checked_out_at)}</span><div className="muted small">Previsão: {dateOnlyLabel(loan.expected_return)}</div></>:'—'}</TableCell><TableCell><div className="keys-actions">{!key.archived_at&&<button className={`btn ${loan?'':'btn-primary'}`} disabled={busy} onClick={()=>openForm(loan?'return':'checkout',key)}>{loan?<ArrowDownLeft/>:<ArrowUpRight/>}{loan?'Devolver':'Retirar'}</button>}<button className="btn btn-ghost" aria-label={`Histórico de ${key.name}`} onClick={()=>setHistoryId(key.id)}><History/>Histórico</button>{!key.archived_at&&<button className="btn btn-ghost" aria-label={`Editar chave ${key.name}`} onClick={()=>openForm('edit',key)}><Pencil/></button>}{isAdmin&&(key.archived_at||!loan)&&<button className="btn btn-ghost" aria-label={`${key.archived_at?'Restaurar':'Arquivar'} chave ${key.name}`} disabled={busy} onClick={()=>setArchive(key)}>{key.archived_at?<ArchiveRestore/>:<Archive/>}</button>}</div></TableCell></TableRow>;})}</TableBody></Table>}{data.keys.length>0&&paginate(currentPage,inventory.length,20,setPage)}
   </section></TabsContent>
   <TabsContent value="reports"><div className="keys-report-actions no-print"><p>Consulte retiradas que estiveram em aberto no período selecionado.</p><div className="heading-actions"><button className="btn" disabled={!reportLoans.length||!!reportError||loading} onClick={()=>window.print()}><Printer/>Imprimir / PDF</button><button className="btn btn-primary" disabled={!reportLoans.length||!!reportError||loading} onClick={exportCSV}><Download/>Exportar CSV</button></div></div><section className="panel keys-report"><div className="keys-filters keys-report-filters no-print"><Field label="Data inicial"><input className="field-input" type="date" value={report.from} onChange={e=>setReport({...report,from:e.target.value})}/></Field><Field label="Data final"><input className="field-input" type="date" value={report.to} onChange={e=>setReport({...report,to:e.target.value})}/></Field><Field label="Pessoa que retirou"><input className="field-input" value={report.person} onChange={e=>setReport({...report,person:e.target.value})} placeholder="Nome da pessoa"/></Field><Field label="Local na retirada"><input className="field-input" value={report.location} onChange={e=>setReport({...report,location:e.target.value})} placeholder="Obra, usina ou endereço"/></Field><div className="form-field"><span>Chave</span><Pick label="Chave do relatório" value={report.keyId} onChange={value=>setReport({...report,keyId:value})} options={[["all","Todas as chaves"],...data.keys.map(key=>[key.id,`${key.name}${key.code?' · '+key.code:''}${key.archived_at?' (arquivada)':''}`] as [string,string])]}/></div><div className="form-field"><span>Situação atual da retirada</span><Pick label="Situação atual da retirada" value={report.status} onChange={value=>setReport({...report,status:value})} options={[["all","Todas as situações"],["out","Retiradas no prazo / sem previsão"],["overdue","Atrasadas"],["returned","Devolvidas"]]}/></div></div>
    <div className="cog-report-title"><strong>VOLTS COG · Relatório de chaves</strong><p>Período: {report.from?dateOnlyLabel(report.from):'Todo o histórico'} a {report.to?dateOnlyLabel(report.to):'sem data final'} · Pessoa: {report.person||'Todas'} · Local: {report.location||'Todos'} · Chave: {data.keys.find(key=>key.id===report.keyId)?.name||'Todas'} · Situação atual: {loanStatuses[report.status]||'Todas'}</p><p>Inclui retiradas anteriores ainda em aberto no período. A situação é a atual, na emissão; não representa a situação ao final do período. Nome e local correspondem ao cadastro na saída.</p><span>{reportLoans.length} retiradas · Emissão: {dateLabel(new Date().toISOString())} · Horário de Brasília</span></div>
    {reportError?<p className="error-box" role="alert">{reportError}</p>:reportLoans.length?<Table className="fleet-table keys-report-table"><TableHeader><TableRow>{['Chave / local','Pessoa','Saída','Previsão','Devolução','Situação atual','Observações'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{reportLoans.map((loan,index)=><TableRow key={loan.id} className={index<(currentReportPage-1)*30||index>=currentReportPage*30?'keys-print-row':''}><TableCell><strong>{loan.key_name}</strong>{loan.key_code&&<div>{loan.key_code}</div>}<div>{loan.key_location}</div><span className="muted small">{keyCategories[loan.key_category]}</span></TableCell><TableCell>{loan.holder}</TableCell><TableCell>{dateLabel(loan.checked_out_at)}<div className="muted small">Por: {loan.checkout_author_name}</div></TableCell><TableCell>{dateOnlyLabel(loan.expected_return)}</TableCell><TableCell>{loan.returned_at?<>{dateLabel(loan.returned_at)}<div className="muted small">Por: {loan.return_author_name}</div></>:'Em aberto'}</TableCell><TableCell><Badge status={loanStatus(loan,today)}/></TableCell><TableCell className="keys-notes">{loan.checkout_notes&&<p><strong>Saída:</strong> {loan.checkout_notes}</p>}{loan.return_notes&&<p><strong>Devolução:</strong> {loan.return_notes}</p>}{!loan.checkout_notes&&!loan.return_notes?'—':null}</TableCell></TableRow>)}</TableBody></Table>:<Empty>Nenhuma retirada corresponde ao período e aos filtros.</Empty>}{paginate(currentReportPage,reportLoans.length,30,setReportPage)}
   </section></TabsContent>
  </Tabs>
  <Dialog open={!!form} onOpenChange={value=>{if(!value&&!busy)setForm(null);}}><DialogContent className="dialog-body cog-dialog keys-dialog" showCloseButton={false}><DialogHeader><DialogTitle>{form?.mode==='create'?'Cadastrar chave':form?.mode==='edit'?'Editar chave':form?.mode==='checkout'?'Registrar retirada':'Registrar devolução'}</DialogTitle><DialogDescription>{form?.key?`${form.key.name}${form.key.code?' · '+form.key.code:''}`:'Cadastre a chave conforme ela sair da empresa. Você também pode deixá-la disponível.'} · Horário de Brasília.</DialogDescription></DialogHeader>{form&&<form onSubmit={save}><fieldset disabled={busy} className="keys-fieldset"><div className="form-grid">
   {(form.mode==='create'||form.mode==='edit')&&<><Field label="Nome da chave *" full><input className="field-input" required maxLength={120} autoFocus value={form.name} onChange={e=>edit('name',e.target.value)} placeholder="Ex.: Portão principal"/></Field><Field label="Código / identificação"><input className="field-input" maxLength={40} value={form.code} onChange={e=>edit('code',e.target.value.toLocaleUpperCase('pt-BR'))} placeholder="Opcional, ex.: CH-001"/></Field><div className="form-field"><span>Categoria *</span><Pick label="Categoria da chave" value={form.category} onChange={value=>edit('category',value)} options={Object.entries(keyCategories)}/></div><Field label="Local *" full><input className="field-input" required maxLength={160} value={form.location} onChange={e=>edit('location',e.target.value)} placeholder="Nome da obra, usina, apartamento ou alojamento"/></Field><Field label="Observações da chave" full><textarea className="field-input" maxLength={4000} value={form.notes} onChange={e=>edit('notes',e.target.value)} placeholder="Identificação, acesso ou cuidados com a chave"/></Field></>}
   {form.mode==='create'&&<div className="full keys-checkout-toggle"><label className="cog-check"><Checkbox checked={form.withCheckout} onCheckedChange={value=>edit('withCheckout',value===true)}/><span>Registrar a retirada desta chave agora</span></label><p className="muted small">Desmarque para cadastrar a chave como disponível.</p></div>}
   {(form.mode==='checkout'||form.mode==='create'&&form.withCheckout)&&checkoutFields}
   {form.mode==='return'&&<><div className="notice full"><span>Retirada por <strong>{form.loan?.holder}</strong> em {form.loan&&dateLabel(form.loan.checked_out_at)}.</span></div><Field label="Data e hora da devolução *" full><input className="field-input" type="datetime-local" required max={localKeyTime()} value={form.returned_at} onChange={e=>edit('returned_at',e.target.value)}/></Field><Field label="Observações da devolução" full><textarea className="field-input" maxLength={4000} value={form.return_notes} onChange={e=>edit('return_notes',e.target.value)} placeholder="Condição da chave ou informações da entrega"/></Field></>}
   {form.mode==='edit'&&<p className="muted small full">As alterações valem para o cadastro e para novas retiradas. Os dados das retiradas anteriores são preservados.</p>}
  </div>{formError&&<p className="error-box" role="alert">{formError}</p>}<div className="dialog-buttons"><button type="button" className="btn" onClick={()=>setForm(null)}>Cancelar</button><button className="btn btn-primary">{busy?'Salvando…':form.mode==='return'?'Confirmar devolução':form.mode==='checkout'?'Confirmar retirada':form.mode==='create'&&form.withCheckout?'Cadastrar e registrar retirada':'Salvar chave'}</button></div></fieldset></form>}</DialogContent></Dialog>
  <Dialog open={!!selectedKey} onOpenChange={value=>{if(!value)setHistoryId('');}}><DialogContent className="dialog-body cog-dialog keys-dialog" showCloseButton={false}><DialogHeader><DialogTitle>Histórico · {selectedKey?.name}</DialogTitle><DialogDescription>{selectedKey?.code?selectedKey.code+' · ':''}{selectedKey?.location} · {selectedKey&&keyCategories[selectedKey.category]}</DialogDescription></DialogHeader>{selectedKey?.notes&&<p className="cog-prewrap">{selectedKey.notes}</p>}<div className="keys-history">{history.length?history.map(loan=><article className="cog-entry" key={loan.id}><div className="cog-entry-head"><strong>{loan.holder}</strong><Badge status={loanStatus(loan,today)}/></div><dl><div><dt>Chave na retirada</dt><dd>{loan.key_name}{loan.key_code?' · '+loan.key_code:''} · {loan.key_location}</dd></div><div><dt>Saída</dt><dd>{dateLabel(loan.checked_out_at)} · Registrada por {loan.checkout_author_name}</dd></div><div><dt>Previsão</dt><dd>{dateOnlyLabel(loan.expected_return)}</dd></div><div><dt>Devolução</dt><dd>{loan.returned_at?`${dateLabel(loan.returned_at)} · Registrada por ${loan.return_author_name}`:'Em aberto'}</dd></div></dl>{loan.checkout_notes&&<p><strong>Saída:</strong> {loan.checkout_notes}</p>}{loan.return_notes&&<p><strong>Devolução:</strong> {loan.return_notes}</p>}</article>):<Empty>Esta chave ainda não teve retiradas registradas.</Empty>}</div><div className="dialog-buttons"><button className="btn" onClick={()=>setHistoryId('')}>Fechar</button><button className="btn btn-primary" onClick={()=>{setReport({from:'',to:'',person:'',location:'',keyId:historyId,status:'all'});setHistoryId('');setTab('reports');}}><FileText/>Relatório desta chave</button></div></DialogContent></Dialog>
  <AlertDialog open={!!archive} onOpenChange={value=>{if(!value&&!busy)setArchive(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{archive?.archived_at?'Restaurar':'Arquivar'} chave?</AlertDialogTitle><AlertDialogDescription>{archive?.name}. {archive?.archived_at?'Ela voltará à lista de chaves disponíveis.':'Ela sairá da lista ativa. Todas as retiradas e devoluções continuarão no histórico e nos relatórios.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><button className="btn btn-primary" disabled={busy} onClick={archiveKey}>{busy?'Salvando…':archive?.archived_at?'Restaurar':'Arquivar'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
