import nodemailer from './vendor/nodemailer/dist/esm/nodemailer.js';
import {randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {sqlite} from './sqlite.mjs';
import {fail,now} from './auth.mjs';
import {supportRecipient,supportRecipientConfigured} from './mail-recipient.mjs';
export const recipient=supportRecipient();
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const keyfile=path.join(root,'data','email.key');
function key(){if(!existsSync(keyfile))writeFileSync(keyfile,randomBytes(32),{mode:0o600});return readFileSync(keyfile)}
function encrypt(s){const iv=randomBytes(12);const c=createCipheriv('aes-256-gcm',key(),iv);return JSON.stringify({iv:iv.toString('hex'),data:Buffer.concat([c.update(s,'utf8'),c.final()]).toString('hex'),tag:c.getAuthTag().toString('hex')})}
function decrypt(s){const v=JSON.parse(s),d=createDecipheriv('aes-256-gcm',key(),Buffer.from(v.iv,'hex'));d.setAuthTag(Buffer.from(v.tag,'hex'));return Buffer.concat([d.update(Buffer.from(v.data,'hex')),d.final()]).toString('utf8')}
function config(){const row=sqlite.prepare("SELECT value FROM settings WHERE key='cog_smtp'").get();return row?JSON.parse(row.value):{host:'smtp.gmail.com',port:465,user:'',enabled:false,secret:''}}
export function mailSettings(){const c=config();return {host:c.host,port:c.port,user:c.user,enabled:!!c.enabled,has_password:!!c.secret,recipient}}
export function saveMail(b){if(b.enabled&&!supportRecipientConfigured(recipient))fail('Configure o destinatário de suporte no servidor antes de ativar o envio.');const prev=config();if(typeof b.host!=='string'||!/^([a-z0-9-]+\.)+[a-z]{2,63}$/i.test(b.host)||b.host.length>253)fail('Informe um servidor SMTP válido.');if(![465,587].includes(Number(b.port)))fail('Use a porta 465 ou 587.');if(typeof b.user!=='string'||!/^\S+@\S+\.\S+$/.test(b.user)||b.user.length>200)fail('Informe o e-mail de envio.');if(b.password!==undefined&&typeof b.password!=='string')fail('Senha SMTP inválida.');if(b.password?.length>256)fail('Senha SMTP muito longa.');const same=prev.host===b.host&&prev.user===b.user;const secret=b.password?encrypt(b.password):same?prev.secret:'';if(b.enabled&&!secret)fail('Informe a senha de aplicativo da conta de envio.');const c={host:b.host.toLowerCase(),port:Number(b.port),user:b.user.trim(),enabled:!!b.enabled,secret};sqlite.prepare("INSERT INTO settings VALUES('cog_smtp',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(c));return mailSettings()}
function transporter(c){return nodemailer.createTransport({host:c.host,port:c.port,secure:c.port===465,requireTLS:true,auth:{user:c.user,pass:decrypt(c.secret)},connectionTimeout:15000,greetingTimeout:15000,socketTimeout:20000,disableFileAccess:true,disableUrlAccess:true,tls:{minVersion:'TLSv1.2'}})}
export async function verifyMail(){const c=config();if(!c.secret)fail('Configure uma conta de envio primeiro.');try{await transporter(c).verify();return {ok:true,message:'Conexão e autenticação SMTP verificadas. Nenhum e-mail de teste foi enviado.'}}catch{fail('Não foi possível autenticar no SMTP. Confira servidor, conta, senha de aplicativo e conexão com a internet.',502)}}
let running=false;
export async function processOutbox(){if(running)return;const c=config();if(!c.enabled||!c.secret||!supportRecipientConfigured(recipient))return;running=true;try{const pending=sqlite.prepare("SELECT * FROM cog_outbox WHERE status IN ('pending','error') AND attempts<5 AND next_attempt<=? ORDER BY next_attempt LIMIT 5").all(now());for(const m of pending){const claimed=sqlite.prepare("UPDATE cog_outbox SET status='sending',attempts=attempts+1 WHERE id=? AND status IN ('pending','error')").run(m.id);if(!claimed.changes)continue;try{const result=await transporter(c).sendMail({from:{name:'VOLTS COG',address:c.user},to:recipient,subject:m.subject,text:m.body,messageId:`<${m.id}@volts-cog.local>`});if(!result.accepted?.length)throw new Error('not-accepted');sqlite.prepare("UPDATE cog_outbox SET status='sent',sent_at=?,error='' WHERE id=?").run(now(),m.id)}catch{sqlite.prepare("UPDATE cog_outbox SET status='error',error=?,next_attempt=? WHERE id=?").run('Falha no envio. Verifique a configuração SMTP e a conexão. Após 5 tentativas, use Tentar novamente.',new Date(Date.now()+Math.min(3600000,60000*2**m.attempts)).toISOString(),m.id)}}}finally{running=false}}
export function startMail(){sqlite.prepare("UPDATE cog_outbox SET status='error',error='Envio interrompido pelo reinício. Verifique o destinatário antes de tentar novamente.',attempts=5 WHERE status='sending'").run();const timer=setInterval(()=>processOutbox().catch(()=>{}),30000);timer.unref();processOutbox().catch(()=>{});}
